### ISSUE TITLE
Add WiFi support

### ISSUE THREAD

**Issue by OToussaint** [syssi/esphome-zb-gw03#34]
I succesfully flashed the router-example to the GW (1.3).
But I'm using it exclusivelly over WiFi.
And only ethernet is working.
Trying to add a wifi section in the yaml file is generating an error:

```
ethernet: [source <unicode string>:38]
  
  Component ethernet cannot be used together with component wifi.
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1
  power_pin: GPIO16

```

**Comment by syssi** [comment]
Please remove the `ethernet` section. You cannot use both simultaneously.

**Comment by OToussaint** [comment]
Obviously I need to.
But the full original file is
```
substitutions:
  name: zb-gw03-router
  device_description: "ZB-GW03 eWeLink Ethernet Zigbee Gateway based Zigbee Router"

packages:
  zb-gw03:
    url: https://github.com/syssi/esphome-zb-gw03
    ref: main
    files:
      - packages/core.yaml
      - packages/status_led.yaml
      - packages/button_pairing_mode.yaml
    refresh: 0s
```
No ethernet section.

Do I need to fork the repo to do my own 
`      - packages/core.yaml`

And the original GW firmware was able to manage both, that would be awesome if the ESPHome version could do the same.
