### ISSUE TITLE
Bluetooth proxy as well as Zigbee possible?

### ISSUE THREAD

**Issue by Toomoch** [syssi/esphome-zb-gw03#54]
Hi, would it be possible to use the [bluetooth proxy](https://esphome.io/components/bluetooth_proxy.html) configuration along with the Zigbee gateway?

Is it as simple as adding this?
```yaml
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
```
